# Generated by Django 3.2.5 on 2021-07-12 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210712_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location_qr',
            name='author',
        ),
    ]
