# Generated by Django 3.2.5 on 2021-07-14 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_location_qr_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('zip', models.CharField(default='', max_length=200)),
                ('latitude', models.CharField(default='', max_length=200)),
                ('longitude', models.CharField(default='', max_length=200)),
                ('country_code', models.CharField(default='', max_length=200)),
                ('timezone', models.CharField(default='', max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
