# Generated by Django 3.2.5 on 2021-07-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='regionName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
