# Generated by Django 3.2.4 on 2021-07-16 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_geolocation_regionname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='Chills',
            new_name='chills',
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='state',
            field=models.CharField(choices=[('Johor', 'Johor'), ('Kedah', 'Kedah'), ('Melaka', 'Melaka'), ('Negeri 9', 'Negeri 9'), ('Pahang', 'Pahang'), ('P.Pinang', 'P.Pinang'), ('Perak', 'Perak'), ('Perlis', 'Perlis'), ('Sabah', 'Sabah'), ('Sarawak', 'Sarawak'), ('Selangor', 'Selangor'), ('Terengganu', 'Terengganu'), ('KL', 'KL'), ('Labuan', 'Labuan'), ('Putrajaya', 'Putrajaya')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='post2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('new', models.CharField(default='', max_length=100)),
                ('cured', models.CharField(default='', max_length=100)),
                ('totalcases', models.CharField(default='', max_length=100)),
                ('newdeath', models.CharField(default='', max_length=100)),
                ('totaldeath', models.CharField(default='', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
