# Generated by Django 3.2.4 on 2021-07-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210716_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post2',
            old_name='author',
            new_name='user',
        ),
    ]
