# Generated by Django 3.2.4 on 2021-07-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_author_post2_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post2',
            old_name='user',
            new_name='author',
        ),
    ]
