# Generated by Django 3.2.4 on 2021-07-16 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_rename_user_post2_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='author',
        ),
        migrations.AddField(
            model_name='post2',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
