# Generated by Django 3.2.4 on 2021-07-16 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20210716_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='user',
        ),
        migrations.AddField(
            model_name='post2',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
