# Generated by Django 3.2.4 on 2021-07-16 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
